// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: subscriptions.proto

package subscriptions

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_subscriptions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type SubscribeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribed    bool                   `protobuf:"varint,1,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_subscriptions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeResponse) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

type GetFollowingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingRequest) Reset() {
	*x = GetFollowingRequest{}
	mi := &file_subscriptions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingRequest) ProtoMessage() {}

func (x *GetFollowingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingRequest.ProtoReflect.Descriptor instead.
func (*GetFollowingRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{2}
}

func (x *GetFollowingRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetFollowingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFollowingResponse) Reset() {
	*x = GetFollowingResponse{}
	mi := &file_subscriptions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFollowingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFollowingResponse) ProtoMessage() {}

func (x *GetFollowingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFollowingResponse.ProtoReflect.Descriptor instead.
func (*GetFollowingResponse) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{3}
}

func (x *GetFollowingResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type IsSubscribedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	TargetUserId  string                 `protobuf:"bytes,2,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSubscribedRequest) Reset() {
	*x = IsSubscribedRequest{}
	mi := &file_subscriptions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSubscribedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSubscribedRequest) ProtoMessage() {}

func (x *IsSubscribedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSubscribedRequest.ProtoReflect.Descriptor instead.
func (*IsSubscribedRequest) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{4}
}

func (x *IsSubscribedRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *IsSubscribedRequest) GetTargetUserId() string {
	if x != nil {
		return x.TargetUserId
	}
	return ""
}

type IsSubscribedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscribed    bool                   `protobuf:"varint,1,opt,name=subscribed,proto3" json:"subscribed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsSubscribedResponse) Reset() {
	*x = IsSubscribedResponse{}
	mi := &file_subscriptions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsSubscribedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsSubscribedResponse) ProtoMessage() {}

func (x *IsSubscribedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subscriptions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsSubscribedResponse.ProtoReflect.Descriptor instead.
func (*IsSubscribedResponse) Descriptor() ([]byte, []int) {
	return file_subscriptions_proto_rawDescGZIP(), []int{5}
}

func (x *IsSubscribedResponse) GetSubscribed() bool {
	if x != nil {
		return x.Subscribed
	}
	return false
}

var File_subscriptions_proto protoreflect.FileDescriptor

const file_subscriptions_proto_rawDesc = "" +
	"\n" +
	"\x13subscriptions.proto\x12\x12meme.subscriptions\"+\n" +
	"\x10SubscribeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"3\n" +
	"\x11SubscribeResponse\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\bR\n" +
	"subscribed\".\n" +
	"\x13GetFollowingRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"1\n" +
	"\x14GetFollowingResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"`\n" +
	"\x13IsSubscribedRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12$\n" +
	"\x0etarget_user_id\x18\x02 \x01(\tR\ftargetUserId\"6\n" +
	"\x14IsSubscribedResponse\x12\x1e\n" +
	"\n" +
	"subscribed\x18\x01 \x01(\bR\n" +
	"subscribed2\xe5\x03\n" +
	"\rSubscriptions\x12X\n" +
	"\tSubscribe\x12$.meme.subscriptions.SubscribeRequest\x1a%.meme.subscriptions.SubscribeResponse\x12Z\n" +
	"\vUnsubscribe\x12$.meme.subscriptions.SubscribeRequest\x1a%.meme.subscriptions.SubscribeResponse\x12X\n" +
	"\tGetStatus\x12$.meme.subscriptions.SubscribeRequest\x1a%.meme.subscriptions.SubscribeResponse\x12a\n" +
	"\fGetFollowing\x12'.meme.subscriptions.GetFollowingRequest\x1a(.meme.subscriptions.GetFollowingResponse\x12a\n" +
	"\fIsSubscribed\x12'.meme.subscriptions.IsSubscribedRequest\x1a(.meme.subscriptions.IsSubscribedResponseB-Z+github.com/materkov/meme9/api/subscriptionsb\x06proto3"

var (
	file_subscriptions_proto_rawDescOnce sync.Once
	file_subscriptions_proto_rawDescData []byte
)

func file_subscriptions_proto_rawDescGZIP() []byte {
	file_subscriptions_proto_rawDescOnce.Do(func() {
		file_subscriptions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_subscriptions_proto_rawDesc), len(file_subscriptions_proto_rawDesc)))
	})
	return file_subscriptions_proto_rawDescData
}

var file_subscriptions_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_subscriptions_proto_goTypes = []any{
	(*SubscribeRequest)(nil),     // 0: meme.subscriptions.SubscribeRequest
	(*SubscribeResponse)(nil),    // 1: meme.subscriptions.SubscribeResponse
	(*GetFollowingRequest)(nil),  // 2: meme.subscriptions.GetFollowingRequest
	(*GetFollowingResponse)(nil), // 3: meme.subscriptions.GetFollowingResponse
	(*IsSubscribedRequest)(nil),  // 4: meme.subscriptions.IsSubscribedRequest
	(*IsSubscribedResponse)(nil), // 5: meme.subscriptions.IsSubscribedResponse
}
var file_subscriptions_proto_depIdxs = []int32{
	0, // 0: meme.subscriptions.Subscriptions.Subscribe:input_type -> meme.subscriptions.SubscribeRequest
	0, // 1: meme.subscriptions.Subscriptions.Unsubscribe:input_type -> meme.subscriptions.SubscribeRequest
	0, // 2: meme.subscriptions.Subscriptions.GetStatus:input_type -> meme.subscriptions.SubscribeRequest
	2, // 3: meme.subscriptions.Subscriptions.GetFollowing:input_type -> meme.subscriptions.GetFollowingRequest
	4, // 4: meme.subscriptions.Subscriptions.IsSubscribed:input_type -> meme.subscriptions.IsSubscribedRequest
	1, // 5: meme.subscriptions.Subscriptions.Subscribe:output_type -> meme.subscriptions.SubscribeResponse
	1, // 6: meme.subscriptions.Subscriptions.Unsubscribe:output_type -> meme.subscriptions.SubscribeResponse
	1, // 7: meme.subscriptions.Subscriptions.GetStatus:output_type -> meme.subscriptions.SubscribeResponse
	3, // 8: meme.subscriptions.Subscriptions.GetFollowing:output_type -> meme.subscriptions.GetFollowingResponse
	5, // 9: meme.subscriptions.Subscriptions.IsSubscribed:output_type -> meme.subscriptions.IsSubscribedResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subscriptions_proto_init() }
func file_subscriptions_proto_init() {
	if File_subscriptions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_subscriptions_proto_rawDesc), len(file_subscriptions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subscriptions_proto_goTypes,
		DependencyIndexes: file_subscriptions_proto_depIdxs,
		MessageInfos:      file_subscriptions_proto_msgTypes,
	}.Build()
	File_subscriptions_proto = out.File
	file_subscriptions_proto_goTypes = nil
	file_subscriptions_proto_depIdxs = nil
}
