// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: likes.proto

package likes

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        string                 `protobuf:"bytes,1,opt,name=postId,proto3" json:"postId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeRequest) Reset() {
	*x = LikeRequest{}
	mi := &file_likes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeRequest) ProtoMessage() {}

func (x *LikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_likes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeRequest.ProtoReflect.Descriptor instead.
func (*LikeRequest) Descriptor() ([]byte, []int) {
	return file_likes_proto_rawDescGZIP(), []int{0}
}

func (x *LikeRequest) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

type LikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Liked         bool                   `protobuf:"varint,1,opt,name=liked,proto3" json:"liked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeResponse) Reset() {
	*x = LikeResponse{}
	mi := &file_likes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeResponse) ProtoMessage() {}

func (x *LikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_likes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeResponse.ProtoReflect.Descriptor instead.
func (*LikeResponse) Descriptor() ([]byte, []int) {
	return file_likes_proto_rawDescGZIP(), []int{1}
}

func (x *LikeResponse) GetLiked() bool {
	if x != nil {
		return x.Liked
	}
	return false
}

var File_likes_proto protoreflect.FileDescriptor

const file_likes_proto_rawDesc = "" +
	"\n" +
	"\vlikes.proto\x12\n" +
	"meme.likes\"%\n" +
	"\vLikeRequest\x12\x16\n" +
	"\x06postId\x18\x01 \x01(\tR\x06postId\"$\n" +
	"\fLikeResponse\x12\x14\n" +
	"\x05liked\x18\x01 \x01(\bR\x05liked2\x7f\n" +
	"\x05Likes\x129\n" +
	"\x04Like\x12\x17.meme.likes.LikeRequest\x1a\x18.meme.likes.LikeResponse\x12;\n" +
	"\x06Unlike\x12\x17.meme.likes.LikeRequest\x1a\x18.meme.likes.LikeResponseB%Z#github.com/materkov/meme9/api/likesb\x06proto3"

var (
	file_likes_proto_rawDescOnce sync.Once
	file_likes_proto_rawDescData []byte
)

func file_likes_proto_rawDescGZIP() []byte {
	file_likes_proto_rawDescOnce.Do(func() {
		file_likes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_likes_proto_rawDesc), len(file_likes_proto_rawDesc)))
	})
	return file_likes_proto_rawDescData
}

var file_likes_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_likes_proto_goTypes = []any{
	(*LikeRequest)(nil),  // 0: meme.likes.LikeRequest
	(*LikeResponse)(nil), // 1: meme.likes.LikeResponse
}
var file_likes_proto_depIdxs = []int32{
	0, // 0: meme.likes.Likes.Like:input_type -> meme.likes.LikeRequest
	0, // 1: meme.likes.Likes.Unlike:input_type -> meme.likes.LikeRequest
	1, // 2: meme.likes.Likes.Like:output_type -> meme.likes.LikeResponse
	1, // 3: meme.likes.Likes.Unlike:output_type -> meme.likes.LikeResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_likes_proto_init() }
func file_likes_proto_init() {
	if File_likes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_likes_proto_rawDesc), len(file_likes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_likes_proto_goTypes,
		DependencyIndexes: file_likes_proto_depIdxs,
		MessageInfos:      file_likes_proto_msgTypes,
	}.Build()
	File_likes_proto = out.File
	file_likes_proto_goTypes = nil
	file_likes_proto_depIdxs = nil
}
