// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: api2.proto

package pb

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Renderers int32

const (
	Renderers_UNKNOWN Renderers = 0
	Renderers_FEED    Renderers = 1
	Renderers_PROFILE Renderers = 2
	Renderers_LOGIN   Renderers = 3
)

var Renderers_name = map[int32]string{
	0: "UNKNOWN",
	1: "FEED",
	2: "PROFILE",
	3: "LOGIN",
}

var Renderers_value = map[string]int32{
	"UNKNOWN": 0,
	"FEED":    1,
	"PROFILE": 2,
	"LOGIN":   3,
}

func (x Renderers) String() string {
	return proto.EnumName(Renderers_name, int32(x))
}

func (Renderers) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{0}
}

type ProfileGetRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *ProfileGetRequest) Reset()         { *m = ProfileGetRequest{} }
func (m *ProfileGetRequest) String() string { return proto.CompactTextString(m) }
func (*ProfileGetRequest) ProtoMessage()    {}
func (*ProfileGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{0}
}
func (m *ProfileGetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfileGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfileGetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfileGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileGetRequest.Merge(m, src)
}
func (m *ProfileGetRequest) XXX_Size() int {
	return m.Size()
}
func (m *ProfileGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileGetRequest proto.InternalMessageInfo

func (m *ProfileGetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProfileGetResponse struct {
	Renderer *ProfileRenderer `protobuf:"bytes,1,opt,name=renderer,proto3" json:"renderer,omitempty"`
}

func (m *ProfileGetResponse) Reset()         { *m = ProfileGetResponse{} }
func (m *ProfileGetResponse) String() string { return proto.CompactTextString(m) }
func (*ProfileGetResponse) ProtoMessage()    {}
func (*ProfileGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{1}
}
func (m *ProfileGetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfileGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfileGetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfileGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileGetResponse.Merge(m, src)
}
func (m *ProfileGetResponse) XXX_Size() int {
	return m.Size()
}
func (m *ProfileGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileGetResponse proto.InternalMessageInfo

func (m *ProfileGetResponse) GetRenderer() *ProfileRenderer {
	if m != nil {
		return m.Renderer
	}
	return nil
}

type ProfileRenderer struct {
	Id     string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Avatar string `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
}

func (m *ProfileRenderer) Reset()         { *m = ProfileRenderer{} }
func (m *ProfileRenderer) String() string { return proto.CompactTextString(m) }
func (*ProfileRenderer) ProtoMessage()    {}
func (*ProfileRenderer) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{2}
}
func (m *ProfileRenderer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProfileRenderer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProfileRenderer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProfileRenderer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProfileRenderer.Merge(m, src)
}
func (m *ProfileRenderer) XXX_Size() int {
	return m.Size()
}
func (m *ProfileRenderer) XXX_DiscardUnknown() {
	xxx_messageInfo_ProfileRenderer.DiscardUnknown(m)
}

var xxx_messageInfo_ProfileRenderer proto.InternalMessageInfo

func (m *ProfileRenderer) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ProfileRenderer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProfileRenderer) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

type FeedGetRequest struct {
}

func (m *FeedGetRequest) Reset()         { *m = FeedGetRequest{} }
func (m *FeedGetRequest) String() string { return proto.CompactTextString(m) }
func (*FeedGetRequest) ProtoMessage()    {}
func (*FeedGetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{3}
}
func (m *FeedGetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedGetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedGetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedGetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedGetRequest.Merge(m, src)
}
func (m *FeedGetRequest) XXX_Size() int {
	return m.Size()
}
func (m *FeedGetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedGetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedGetRequest proto.InternalMessageInfo

type FeedGetResponse struct {
	Renderer *FeedRenderer `protobuf:"bytes,1,opt,name=renderer,proto3" json:"renderer,omitempty"`
}

func (m *FeedGetResponse) Reset()         { *m = FeedGetResponse{} }
func (m *FeedGetResponse) String() string { return proto.CompactTextString(m) }
func (*FeedGetResponse) ProtoMessage()    {}
func (*FeedGetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{4}
}
func (m *FeedGetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedGetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedGetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedGetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedGetResponse.Merge(m, src)
}
func (m *FeedGetResponse) XXX_Size() int {
	return m.Size()
}
func (m *FeedGetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedGetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedGetResponse proto.InternalMessageInfo

func (m *FeedGetResponse) GetRenderer() *FeedRenderer {
	if m != nil {
		return m.Renderer
	}
	return nil
}

type FeedRenderer struct {
	Posts []*FeedRenderer_Post `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
}

func (m *FeedRenderer) Reset()         { *m = FeedRenderer{} }
func (m *FeedRenderer) String() string { return proto.CompactTextString(m) }
func (*FeedRenderer) ProtoMessage()    {}
func (*FeedRenderer) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{5}
}
func (m *FeedRenderer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedRenderer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedRenderer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedRenderer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedRenderer.Merge(m, src)
}
func (m *FeedRenderer) XXX_Size() int {
	return m.Size()
}
func (m *FeedRenderer) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedRenderer.DiscardUnknown(m)
}

var xxx_messageInfo_FeedRenderer proto.InternalMessageInfo

func (m *FeedRenderer) GetPosts() []*FeedRenderer_Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

type FeedRenderer_Post struct {
	Id           string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId     string `protobuf:"bytes,2,opt,name=authorId,proto3" json:"authorId,omitempty"`
	AuthorAvatar string `protobuf:"bytes,3,opt,name=authorAvatar,proto3" json:"authorAvatar,omitempty"`
	AuthorName   string `protobuf:"bytes,4,opt,name=authorName,proto3" json:"authorName,omitempty"`
	AuthorUrl    string `protobuf:"bytes,8,opt,name=authorUrl,proto3" json:"authorUrl,omitempty"`
	DateDisplay  string `protobuf:"bytes,5,opt,name=dateDisplay,proto3" json:"dateDisplay,omitempty"`
	Text         string `protobuf:"bytes,6,opt,name=text,proto3" json:"text,omitempty"`
	ImageUrl     string `protobuf:"bytes,7,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
}

func (m *FeedRenderer_Post) Reset()         { *m = FeedRenderer_Post{} }
func (m *FeedRenderer_Post) String() string { return proto.CompactTextString(m) }
func (*FeedRenderer_Post) ProtoMessage()    {}
func (*FeedRenderer_Post) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{5, 0}
}
func (m *FeedRenderer_Post) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedRenderer_Post) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedRenderer_Post.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedRenderer_Post) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedRenderer_Post.Merge(m, src)
}
func (m *FeedRenderer_Post) XXX_Size() int {
	return m.Size()
}
func (m *FeedRenderer_Post) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedRenderer_Post.DiscardUnknown(m)
}

var xxx_messageInfo_FeedRenderer_Post proto.InternalMessageInfo

func (m *FeedRenderer_Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FeedRenderer_Post) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *FeedRenderer_Post) GetAuthorAvatar() string {
	if m != nil {
		return m.AuthorAvatar
	}
	return ""
}

func (m *FeedRenderer_Post) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func (m *FeedRenderer_Post) GetAuthorUrl() string {
	if m != nil {
		return m.AuthorUrl
	}
	return ""
}

func (m *FeedRenderer_Post) GetDateDisplay() string {
	if m != nil {
		return m.DateDisplay
	}
	return ""
}

func (m *FeedRenderer_Post) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *FeedRenderer_Post) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

type FeedGetHeaderRequest struct {
}

func (m *FeedGetHeaderRequest) Reset()         { *m = FeedGetHeaderRequest{} }
func (m *FeedGetHeaderRequest) String() string { return proto.CompactTextString(m) }
func (*FeedGetHeaderRequest) ProtoMessage()    {}
func (*FeedGetHeaderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{6}
}
func (m *FeedGetHeaderRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedGetHeaderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedGetHeaderRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedGetHeaderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedGetHeaderRequest.Merge(m, src)
}
func (m *FeedGetHeaderRequest) XXX_Size() int {
	return m.Size()
}
func (m *FeedGetHeaderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedGetHeaderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FeedGetHeaderRequest proto.InternalMessageInfo

type FeedGetHeaderResponse struct {
	Renderer *HeaderRenderer `protobuf:"bytes,1,opt,name=renderer,proto3" json:"renderer,omitempty"`
}

func (m *FeedGetHeaderResponse) Reset()         { *m = FeedGetHeaderResponse{} }
func (m *FeedGetHeaderResponse) String() string { return proto.CompactTextString(m) }
func (*FeedGetHeaderResponse) ProtoMessage()    {}
func (*FeedGetHeaderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{7}
}
func (m *FeedGetHeaderResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FeedGetHeaderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FeedGetHeaderResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FeedGetHeaderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FeedGetHeaderResponse.Merge(m, src)
}
func (m *FeedGetHeaderResponse) XXX_Size() int {
	return m.Size()
}
func (m *FeedGetHeaderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FeedGetHeaderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FeedGetHeaderResponse proto.InternalMessageInfo

func (m *FeedGetHeaderResponse) GetRenderer() *HeaderRenderer {
	if m != nil {
		return m.Renderer
	}
	return nil
}

type HeaderRenderer struct {
	MainUrl      string `protobuf:"bytes,1,opt,name=mainUrl,proto3" json:"mainUrl,omitempty"`
	UserName     string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	UserAvatar   string `protobuf:"bytes,3,opt,name=userAvatar,proto3" json:"userAvatar,omitempty"`
	IsAuthorized bool   `protobuf:"varint,4,opt,name=isAuthorized,proto3" json:"isAuthorized,omitempty"`
}

func (m *HeaderRenderer) Reset()         { *m = HeaderRenderer{} }
func (m *HeaderRenderer) String() string { return proto.CompactTextString(m) }
func (*HeaderRenderer) ProtoMessage()    {}
func (*HeaderRenderer) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{8}
}
func (m *HeaderRenderer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *HeaderRenderer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_HeaderRenderer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *HeaderRenderer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HeaderRenderer.Merge(m, src)
}
func (m *HeaderRenderer) XXX_Size() int {
	return m.Size()
}
func (m *HeaderRenderer) XXX_DiscardUnknown() {
	xxx_messageInfo_HeaderRenderer.DiscardUnknown(m)
}

var xxx_messageInfo_HeaderRenderer proto.InternalMessageInfo

func (m *HeaderRenderer) GetMainUrl() string {
	if m != nil {
		return m.MainUrl
	}
	return ""
}

func (m *HeaderRenderer) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *HeaderRenderer) GetUserAvatar() string {
	if m != nil {
		return m.UserAvatar
	}
	return ""
}

func (m *HeaderRenderer) GetIsAuthorized() bool {
	if m != nil {
		return m.IsAuthorized
	}
	return false
}

type ResolveRouteResponse struct {
	Renderer Renderers `protobuf:"varint,1,opt,name=renderer,proto3,enum=meme.Renderers" json:"renderer,omitempty"`
}

func (m *ResolveRouteResponse) Reset()         { *m = ResolveRouteResponse{} }
func (m *ResolveRouteResponse) String() string { return proto.CompactTextString(m) }
func (*ResolveRouteResponse) ProtoMessage()    {}
func (*ResolveRouteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_592802a36db5ccc7, []int{9}
}
func (m *ResolveRouteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ResolveRouteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ResolveRouteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ResolveRouteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResolveRouteResponse.Merge(m, src)
}
func (m *ResolveRouteResponse) XXX_Size() int {
	return m.Size()
}
func (m *ResolveRouteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResolveRouteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResolveRouteResponse proto.InternalMessageInfo

func (m *ResolveRouteResponse) GetRenderer() Renderers {
	if m != nil {
		return m.Renderer
	}
	return Renderers_UNKNOWN
}

func init() {
	proto.RegisterEnum("meme.Renderers", Renderers_name, Renderers_value)
	proto.RegisterType((*ProfileGetRequest)(nil), "meme.ProfileGetRequest")
	proto.RegisterType((*ProfileGetResponse)(nil), "meme.ProfileGetResponse")
	proto.RegisterType((*ProfileRenderer)(nil), "meme.ProfileRenderer")
	proto.RegisterType((*FeedGetRequest)(nil), "meme.FeedGetRequest")
	proto.RegisterType((*FeedGetResponse)(nil), "meme.FeedGetResponse")
	proto.RegisterType((*FeedRenderer)(nil), "meme.FeedRenderer")
	proto.RegisterType((*FeedRenderer_Post)(nil), "meme.FeedRenderer.Post")
	proto.RegisterType((*FeedGetHeaderRequest)(nil), "meme.FeedGetHeaderRequest")
	proto.RegisterType((*FeedGetHeaderResponse)(nil), "meme.FeedGetHeaderResponse")
	proto.RegisterType((*HeaderRenderer)(nil), "meme.HeaderRenderer")
	proto.RegisterType((*ResolveRouteResponse)(nil), "meme.ResolveRouteResponse")
}

func init() { proto.RegisterFile("api2.proto", fileDescriptor_592802a36db5ccc7) }

var fileDescriptor_592802a36db5ccc7 = []byte{
	// 569 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x54, 0x4d, 0x8f, 0xd2, 0x4e,
	0x18, 0xa7, 0xa5, 0xbc, 0x3d, 0x6c, 0x80, 0xff, 0x04, 0x76, 0x1b, 0xfe, 0x9b, 0x86, 0xd4, 0xcb,
	0x46, 0x23, 0xd1, 0x7a, 0x31, 0xde, 0x70, 0x79, 0x91, 0xb8, 0x02, 0x69, 0xb2, 0x31, 0xf1, 0x36,
	0x9b, 0x3e, 0x6a, 0x13, 0xa0, 0xb5, 0x33, 0x6c, 0xd4, 0x93, 0x67, 0x4f, 0x7e, 0x0a, 0x3f, 0x8b,
	0xc7, 0x3d, 0x7a, 0x34, 0x90, 0xf8, 0x39, 0xcc, 0x74, 0xda, 0xd2, 0x97, 0xbd, 0xcd, 0xef, 0x85,
	0xe1, 0xf7, 0xfc, 0x1e, 0x06, 0x00, 0xea, 0xbb, 0xd6, 0xd0, 0x0f, 0x3c, 0xee, 0x11, 0x6d, 0x83,
	0x1b, 0x34, 0x1f, 0xc0, 0x7f, 0xab, 0xc0, 0x7b, 0xef, 0xae, 0x71, 0x86, 0xdc, 0xc6, 0x4f, 0x3b,
	0x64, 0x9c, 0xb4, 0x40, 0x75, 0x1d, 0x5d, 0x19, 0x28, 0x17, 0x0d, 0x5b, 0x75, 0x1d, 0x73, 0x06,
	0x24, 0x6d, 0x62, 0xbe, 0xb7, 0x65, 0x48, 0x9e, 0x42, 0x3d, 0xc0, 0xad, 0x83, 0x01, 0x06, 0xa1,
	0xb7, 0x69, 0xf5, 0x86, 0xe2, 0xce, 0x61, 0xe4, 0xb5, 0x23, 0xd1, 0x4e, 0x6c, 0xe6, 0x1b, 0x68,
	0xe7, 0xc4, 0xfc, 0x77, 0x11, 0x02, 0xda, 0x96, 0x6e, 0x50, 0x57, 0x43, 0x26, 0x3c, 0x93, 0x53,
	0xa8, 0xd2, 0x5b, 0xca, 0x69, 0xa0, 0x97, 0x43, 0x36, 0x42, 0x66, 0x07, 0x5a, 0x53, 0x44, 0xe7,
	0x98, 0xdc, 0x1c, 0x41, 0x3b, 0x61, 0xa2, 0x98, 0xc3, 0x42, 0x4c, 0x22, 0x63, 0x0a, 0xe3, 0x3d,
	0x19, 0x7f, 0xaa, 0x70, 0x92, 0x96, 0xc8, 0x63, 0xa8, 0xf8, 0x1e, 0xe3, 0x4c, 0x57, 0x06, 0xe5,
	0x8b, 0xa6, 0x75, 0x56, 0xfc, 0xf4, 0x70, 0xe5, 0x31, 0x6e, 0x4b, 0x57, 0xff, 0xaf, 0x02, 0x9a,
	0xc0, 0x85, 0xc9, 0xfa, 0x50, 0xa7, 0x3b, 0xfe, 0xd1, 0x0b, 0xe6, 0x4e, 0x34, 0x5d, 0x82, 0x89,
	0x09, 0x27, 0xf2, 0x3c, 0x4a, 0xcf, 0x99, 0xe1, 0x88, 0x01, 0x20, 0xf1, 0x42, 0xf4, 0xa3, 0x85,
	0x8e, 0x14, 0x43, 0xce, 0xa1, 0x21, 0xd1, 0x75, 0xb0, 0xd6, 0xeb, 0xa1, 0x7c, 0x24, 0xc8, 0x00,
	0x9a, 0x0e, 0xe5, 0x38, 0x76, 0x99, 0xbf, 0xa6, 0x5f, 0xf4, 0x4a, 0xa8, 0xa7, 0x29, 0xd1, 0x3c,
	0xc7, 0xcf, 0x5c, 0xaf, 0xca, 0xe6, 0xc5, 0x59, 0x64, 0x76, 0x37, 0xf4, 0x03, 0x8a, 0x2b, 0x6b,
	0x32, 0x73, 0x8c, 0xcd, 0x53, 0xe8, 0x46, 0x5d, 0xbf, 0x42, 0xea, 0x60, 0x10, 0xef, 0x60, 0x0e,
	0xbd, 0x1c, 0x1f, 0x6d, 0xe2, 0x49, 0x61, 0x13, 0x5d, 0xd9, 0x65, 0xec, 0x2b, 0xec, 0xe2, 0xbb,
	0x02, 0xad, 0xac, 0x48, 0x74, 0xa8, 0x6d, 0xa8, 0xbb, 0x15, 0x81, 0x64, 0xb5, 0x31, 0x14, 0x59,
	0x77, 0x0c, 0x65, 0x3b, 0x51, 0xbf, 0x31, 0x16, 0xdd, 0x89, 0x73, 0xa6, 0xdd, 0x14, 0x23, 0xfa,
	0x77, 0xd9, 0x28, 0x2c, 0xcb, 0xfd, 0x8a, 0x4e, 0xd8, 0x6e, 0xdd, 0xce, 0x70, 0xe6, 0x25, 0x74,
	0x6d, 0x64, 0xde, 0xfa, 0x16, 0x6d, 0x6f, 0xc7, 0x31, 0x19, 0xeb, 0x51, 0x6e, 0xac, 0x96, 0xd5,
	0x96, 0x63, 0xc5, 0x99, 0xd9, 0x71, 0xa2, 0x87, 0x2f, 0xa0, 0x91, 0xd0, 0xa4, 0x09, 0xb5, 0xeb,
	0xc5, 0xeb, 0xc5, 0xf2, 0xed, 0xa2, 0x53, 0x22, 0x75, 0xd0, 0xa6, 0x93, 0xc9, 0xb8, 0xa3, 0x08,
	0x7a, 0x65, 0x2f, 0xa7, 0xf3, 0xab, 0x49, 0x47, 0x25, 0x0d, 0xa8, 0x5c, 0x2d, 0x67, 0xf3, 0x45,
	0xa7, 0x6c, 0x7d, 0x53, 0x40, 0x13, 0xcd, 0x12, 0x0b, 0xca, 0x33, 0xe4, 0xa4, 0x7b, 0xfc, 0x25,
	0x1e, 0x9f, 0x40, 0xbf, 0x97, 0x63, 0xa3, 0x94, 0x63, 0x68, 0x24, 0x1b, 0x21, 0xfd, 0x8c, 0x27,
	0xb3, 0xbe, 0xfe, 0xff, 0xf7, 0x6a, 0xf2, 0x16, 0xeb, 0x12, 0x6a, 0xd1, 0x03, 0x26, 0xcf, 0x65,
	0x88, 0xb3, 0xcc, 0x9b, 0x4f, 0xe5, 0xd0, 0x8b, 0x82, 0xbc, 0xe4, 0xe5, 0xf9, 0xaf, 0xbd, 0xa1,
	0xdc, 0xed, 0x0d, 0xe5, 0xcf, 0xde, 0x50, 0x7e, 0x1c, 0x8c, 0xd2, 0xdd, 0xc1, 0x28, 0xfd, 0x3e,
	0x18, 0xa5, 0x77, 0xaa, 0x7f, 0x73, 0x53, 0x0d, 0xff, 0x9e, 0x9e, 0xfd, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x4b, 0xcc, 0x28, 0x3b, 0xac, 0x04, 0x00, 0x00,
}

func (m *ProfileGetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfileGetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileGetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProfileGetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfileGetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileGetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Renderer != nil {
		{
			size, err := m.Renderer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApi2(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProfileRenderer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProfileRenderer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProfileRenderer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Avatar) > 0 {
		i -= len(m.Avatar)
		copy(dAtA[i:], m.Avatar)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.Avatar)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FeedGetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedGetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedGetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *FeedGetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedGetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedGetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Renderer != nil {
		{
			size, err := m.Renderer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApi2(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FeedRenderer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedRenderer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedRenderer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Posts) > 0 {
		for iNdEx := len(m.Posts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Posts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintApi2(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *FeedRenderer_Post) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedRenderer_Post) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedRenderer_Post) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AuthorUrl) > 0 {
		i -= len(m.AuthorUrl)
		copy(dAtA[i:], m.AuthorUrl)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.AuthorUrl)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.ImageUrl) > 0 {
		i -= len(m.ImageUrl)
		copy(dAtA[i:], m.ImageUrl)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.ImageUrl)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.Text) > 0 {
		i -= len(m.Text)
		copy(dAtA[i:], m.Text)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.Text)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DateDisplay) > 0 {
		i -= len(m.DateDisplay)
		copy(dAtA[i:], m.DateDisplay)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.DateDisplay)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.AuthorName) > 0 {
		i -= len(m.AuthorName)
		copy(dAtA[i:], m.AuthorName)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.AuthorName)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.AuthorAvatar) > 0 {
		i -= len(m.AuthorAvatar)
		copy(dAtA[i:], m.AuthorAvatar)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.AuthorAvatar)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AuthorId) > 0 {
		i -= len(m.AuthorId)
		copy(dAtA[i:], m.AuthorId)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.AuthorId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *FeedGetHeaderRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedGetHeaderRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedGetHeaderRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *FeedGetHeaderResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FeedGetHeaderResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FeedGetHeaderResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Renderer != nil {
		{
			size, err := m.Renderer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintApi2(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *HeaderRenderer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *HeaderRenderer) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *HeaderRenderer) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsAuthorized {
		i--
		if m.IsAuthorized {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.UserAvatar) > 0 {
		i -= len(m.UserAvatar)
		copy(dAtA[i:], m.UserAvatar)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.UserAvatar)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.UserName) > 0 {
		i -= len(m.UserName)
		copy(dAtA[i:], m.UserName)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.UserName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.MainUrl) > 0 {
		i -= len(m.MainUrl)
		copy(dAtA[i:], m.MainUrl)
		i = encodeVarintApi2(dAtA, i, uint64(len(m.MainUrl)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ResolveRouteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResolveRouteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResolveRouteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Renderer != 0 {
		i = encodeVarintApi2(dAtA, i, uint64(m.Renderer))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintApi2(dAtA []byte, offset int, v uint64) int {
	offset -= sovApi2(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProfileGetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	return n
}

func (m *ProfileGetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Renderer != nil {
		l = m.Renderer.Size()
		n += 1 + l + sovApi2(uint64(l))
	}
	return n
}

func (m *ProfileRenderer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.Avatar)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	return n
}

func (m *FeedGetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *FeedGetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Renderer != nil {
		l = m.Renderer.Size()
		n += 1 + l + sovApi2(uint64(l))
	}
	return n
}

func (m *FeedRenderer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Posts) > 0 {
		for _, e := range m.Posts {
			l = e.Size()
			n += 1 + l + sovApi2(uint64(l))
		}
	}
	return n
}

func (m *FeedRenderer_Post) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.AuthorId)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.AuthorAvatar)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.AuthorName)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.DateDisplay)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.Text)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.ImageUrl)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.AuthorUrl)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	return n
}

func (m *FeedGetHeaderRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *FeedGetHeaderResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Renderer != nil {
		l = m.Renderer.Size()
		n += 1 + l + sovApi2(uint64(l))
	}
	return n
}

func (m *HeaderRenderer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.MainUrl)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.UserName)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	l = len(m.UserAvatar)
	if l > 0 {
		n += 1 + l + sovApi2(uint64(l))
	}
	if m.IsAuthorized {
		n += 2
	}
	return n
}

func (m *ResolveRouteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Renderer != 0 {
		n += 1 + sovApi2(uint64(m.Renderer))
	}
	return n
}

func sovApi2(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozApi2(x uint64) (n int) {
	return sovApi2(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProfileGetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfileGetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfileGetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProfileGetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfileGetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfileGetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Renderer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Renderer == nil {
				m.Renderer = &ProfileRenderer{}
			}
			if err := m.Renderer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProfileRenderer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProfileRenderer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProfileRenderer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Avatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Avatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedGetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedGetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedGetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedGetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedGetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedGetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Renderer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Renderer == nil {
				m.Renderer = &FeedRenderer{}
			}
			if err := m.Renderer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedRenderer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedRenderer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedRenderer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Posts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Posts = append(m.Posts, &FeedRenderer_Post{})
			if err := m.Posts[len(m.Posts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedRenderer_Post) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Post: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Post: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorAvatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorAvatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DateDisplay", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DateDisplay = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Text", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Text = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ImageUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ImageUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AuthorUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AuthorUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedGetHeaderRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedGetHeaderRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedGetHeaderRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FeedGetHeaderResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FeedGetHeaderResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FeedGetHeaderResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Renderer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Renderer == nil {
				m.Renderer = &HeaderRenderer{}
			}
			if err := m.Renderer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *HeaderRenderer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: HeaderRenderer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: HeaderRenderer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MainUrl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MainUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UserAvatar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthApi2
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthApi2
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UserAvatar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsAuthorized", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsAuthorized = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ResolveRouteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ResolveRouteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ResolveRouteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Renderer", wireType)
			}
			m.Renderer = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Renderer |= Renderers(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipApi2(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthApi2
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipApi2(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowApi2
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowApi2
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthApi2
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupApi2
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthApi2
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthApi2        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowApi2          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupApi2 = fmt.Errorf("proto: unexpected end of group")
)
