// Code generated by protoc-gen-twirp v8.0.0, DO NOT EDIT.
// source: posts.proto

package pb

import context "context"
import fmt "fmt"
import http "net/http"
import ioutil "io/ioutil"
import json "encoding/json"
import strconv "strconv"
import strings "strings"

import protojson "google.golang.org/protobuf/encoding/protojson"
import proto "google.golang.org/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// This is a compile-time assertion to ensure that this generated file
// is compatible with the twirp package used in your project.
// A compilation error at this line likely means your copy of the
// twirp package needs to be updated.
const _ = twirp.TwirpPackageIsVersion7

// ===============
// Posts Interface
// ===============

type Posts interface {
	Add(context.Context, *PostsAddRequest) (*PostsAddResponse, error)

	ToggleLike(context.Context, *ToggleLikeRequest) (*ToggleLikeResponse, error)

	AddComment(context.Context, *AddCommentRequest) (*AddCommentResponse, error)
}

// =====================
// Posts Protobuf Client
// =====================

type postsProtobufClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewPostsProtobufClient creates a Protobuf client that implements the Posts interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewPostsProtobufClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Posts {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(clientOpts.PathPrefix(), "meme", "Posts")
	urls := [3]string{
		serviceURL + "Add",
		serviceURL + "ToggleLike",
		serviceURL + "AddComment",
	}

	return &postsProtobufClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *postsProtobufClient) Add(ctx context.Context, in *PostsAddRequest) (*PostsAddResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "meme")
	ctx = ctxsetters.WithServiceName(ctx, "Posts")
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	caller := c.callAdd
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *PostsAddRequest) (*PostsAddResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PostsAddRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PostsAddRequest) when calling interceptor")
					}
					return c.callAdd(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PostsAddResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PostsAddResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postsProtobufClient) callAdd(ctx context.Context, in *PostsAddRequest) (*PostsAddResponse, error) {
	out := new(PostsAddResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postsProtobufClient) ToggleLike(ctx context.Context, in *ToggleLikeRequest) (*ToggleLikeResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "meme")
	ctx = ctxsetters.WithServiceName(ctx, "Posts")
	ctx = ctxsetters.WithMethodName(ctx, "ToggleLike")
	caller := c.callToggleLike
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ToggleLikeRequest) (*ToggleLikeResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ToggleLikeRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ToggleLikeRequest) when calling interceptor")
					}
					return c.callToggleLike(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ToggleLikeResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ToggleLikeResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postsProtobufClient) callToggleLike(ctx context.Context, in *ToggleLikeRequest) (*ToggleLikeResponse, error) {
	out := new(ToggleLikeResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postsProtobufClient) AddComment(ctx context.Context, in *AddCommentRequest) (*AddCommentResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "meme")
	ctx = ctxsetters.WithServiceName(ctx, "Posts")
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	caller := c.callAddComment
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *AddCommentRequest) (*AddCommentResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AddCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AddCommentRequest) when calling interceptor")
					}
					return c.callAddComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AddCommentResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AddCommentResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postsProtobufClient) callAddComment(ctx context.Context, in *AddCommentRequest) (*AddCommentResponse, error) {
	out := new(AddCommentResponse)
	ctx, err := doProtobufRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// =================
// Posts JSON Client
// =================

type postsJSONClient struct {
	client      HTTPClient
	urls        [3]string
	interceptor twirp.Interceptor
	opts        twirp.ClientOptions
}

// NewPostsJSONClient creates a JSON client that implements the Posts interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewPostsJSONClient(baseURL string, client HTTPClient, opts ...twirp.ClientOption) Posts {
	if c, ok := client.(*http.Client); ok {
		client = withoutRedirects(c)
	}

	clientOpts := twirp.ClientOptions{}
	for _, o := range opts {
		o(&clientOpts)
	}

	// Build method URLs: <baseURL>[<prefix>]/<package>.<Service>/<Method>
	serviceURL := sanitizeBaseURL(baseURL)
	serviceURL += baseServicePath(clientOpts.PathPrefix(), "meme", "Posts")
	urls := [3]string{
		serviceURL + "Add",
		serviceURL + "ToggleLike",
		serviceURL + "AddComment",
	}

	return &postsJSONClient{
		client:      client,
		urls:        urls,
		interceptor: twirp.ChainInterceptors(clientOpts.Interceptors...),
		opts:        clientOpts,
	}
}

func (c *postsJSONClient) Add(ctx context.Context, in *PostsAddRequest) (*PostsAddResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "meme")
	ctx = ctxsetters.WithServiceName(ctx, "Posts")
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	caller := c.callAdd
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *PostsAddRequest) (*PostsAddResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PostsAddRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PostsAddRequest) when calling interceptor")
					}
					return c.callAdd(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PostsAddResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PostsAddResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postsJSONClient) callAdd(ctx context.Context, in *PostsAddRequest) (*PostsAddResponse, error) {
	out := new(PostsAddResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[0], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postsJSONClient) ToggleLike(ctx context.Context, in *ToggleLikeRequest) (*ToggleLikeResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "meme")
	ctx = ctxsetters.WithServiceName(ctx, "Posts")
	ctx = ctxsetters.WithMethodName(ctx, "ToggleLike")
	caller := c.callToggleLike
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *ToggleLikeRequest) (*ToggleLikeResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ToggleLikeRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ToggleLikeRequest) when calling interceptor")
					}
					return c.callToggleLike(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ToggleLikeResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ToggleLikeResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postsJSONClient) callToggleLike(ctx context.Context, in *ToggleLikeRequest) (*ToggleLikeResponse, error) {
	out := new(ToggleLikeResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[1], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

func (c *postsJSONClient) AddComment(ctx context.Context, in *AddCommentRequest) (*AddCommentResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "meme")
	ctx = ctxsetters.WithServiceName(ctx, "Posts")
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	caller := c.callAddComment
	if c.interceptor != nil {
		caller = func(ctx context.Context, req *AddCommentRequest) (*AddCommentResponse, error) {
			resp, err := c.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AddCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AddCommentRequest) when calling interceptor")
					}
					return c.callAddComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AddCommentResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AddCommentResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}
	return caller(ctx, in)
}

func (c *postsJSONClient) callAddComment(ctx context.Context, in *AddCommentRequest) (*AddCommentResponse, error) {
	out := new(AddCommentResponse)
	ctx, err := doJSONRequest(ctx, c.client, c.opts.Hooks, c.urls[2], in, out)
	if err != nil {
		twerr, ok := err.(twirp.Error)
		if !ok {
			twerr = twirp.InternalErrorWith(err)
		}
		callClientError(ctx, c.opts.Hooks, twerr)
		return nil, err
	}

	callClientResponseReceived(ctx, c.opts.Hooks)

	return out, nil
}

// ====================
// Posts Server Handler
// ====================

type postsServer struct {
	Posts
	interceptor      twirp.Interceptor
	hooks            *twirp.ServerHooks
	pathPrefix       string // prefix for routing
	jsonSkipDefaults bool   // do not include unpopulated fields (default values) in the response
}

// NewPostsServer builds a TwirpServer that can be used as an http.Handler to handle
// HTTP requests that are routed to the right method in the provided svc implementation.
// The opts are twirp.ServerOption modifiers, for example twirp.WithServerHooks(hooks).
func NewPostsServer(svc Posts, opts ...interface{}) TwirpServer {
	serverOpts := twirp.ServerOptions{}
	for _, opt := range opts {
		switch o := opt.(type) {
		case twirp.ServerOption:
			o(&serverOpts)
		case *twirp.ServerHooks: // backwards compatibility, allow to specify hooks as an argument
			twirp.WithServerHooks(o)(&serverOpts)
		case nil: // backwards compatibility, allow nil value for the argument
			continue
		default:
			panic(fmt.Sprintf("Invalid option type %T on NewPostsServer", o))
		}
	}

	return &postsServer{
		Posts:            svc,
		pathPrefix:       serverOpts.PathPrefix(),
		interceptor:      twirp.ChainInterceptors(serverOpts.Interceptors...),
		hooks:            serverOpts.Hooks,
		jsonSkipDefaults: serverOpts.JSONSkipDefaults,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *postsServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// handleRequestBodyError is used to handle error when the twirp server cannot read request
func (s *postsServer) handleRequestBodyError(ctx context.Context, resp http.ResponseWriter, msg string, err error) {
	if context.Canceled == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.Canceled, "failed to read request: context canceled"))
		return
	}
	if context.DeadlineExceeded == ctx.Err() {
		s.writeError(ctx, resp, twirp.NewError(twirp.DeadlineExceeded, "failed to read request: deadline exceeded"))
		return
	}
	s.writeError(ctx, resp, twirp.WrapError(malformedRequestError(msg), err))
}

// PostsPathPrefix is a convenience constant that could used to identify URL paths.
// Should be used with caution, it only matches routes generated by Twirp Go clients,
// that add a "/twirp" prefix by default, and use CamelCase service and method names.
// More info: https://twitchtv.github.io/twirp/docs/routing.html
const PostsPathPrefix = "/twirp/meme.Posts/"

func (s *postsServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "meme")
	ctx = ctxsetters.WithServiceName(ctx, "Posts")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	// Verify path format: [<prefix>]/<package>.<Service>/<Method>
	prefix, pkgService, method := parseTwirpPath(req.URL.Path)
	if pkgService != "meme.Posts" {
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
	if prefix != s.pathPrefix {
		msg := fmt.Sprintf("invalid path prefix %q, expected %q, on path %q", prefix, s.pathPrefix, req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}

	switch method {
	case "Add":
		s.serveAdd(ctx, resp, req)
		return
	case "ToggleLike":
		s.serveToggleLike(ctx, resp, req)
		return
	case "AddComment":
		s.serveAddComment(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		s.writeError(ctx, resp, badRouteError(msg, req.Method, req.URL.Path))
		return
	}
}

func (s *postsServer) serveAdd(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAddJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAddProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postsServer) serveAddJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(PostsAddRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Posts.Add
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *PostsAddRequest) (*PostsAddResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PostsAddRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PostsAddRequest) when calling interceptor")
					}
					return s.Posts.Add(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PostsAddResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PostsAddResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *PostsAddResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PostsAddResponse and nil error while calling Add. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postsServer) serveAddProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "Add")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(PostsAddRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Posts.Add
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *PostsAddRequest) (*PostsAddResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*PostsAddRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*PostsAddRequest) when calling interceptor")
					}
					return s.Posts.Add(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*PostsAddResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*PostsAddResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *PostsAddResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *PostsAddResponse and nil error while calling Add. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postsServer) serveToggleLike(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveToggleLikeJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveToggleLikeProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postsServer) serveToggleLikeJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ToggleLike")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(ToggleLikeRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Posts.ToggleLike
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ToggleLikeRequest) (*ToggleLikeResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ToggleLikeRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ToggleLikeRequest) when calling interceptor")
					}
					return s.Posts.ToggleLike(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ToggleLikeResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ToggleLikeResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ToggleLikeResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ToggleLikeResponse and nil error while calling ToggleLike. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postsServer) serveToggleLikeProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ToggleLike")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(ToggleLikeRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Posts.ToggleLike
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *ToggleLikeRequest) (*ToggleLikeResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*ToggleLikeRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*ToggleLikeRequest) when calling interceptor")
					}
					return s.Posts.ToggleLike(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*ToggleLikeResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*ToggleLikeResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *ToggleLikeResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ToggleLikeResponse and nil error while calling ToggleLike. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postsServer) serveAddComment(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveAddCommentJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveAddCommentProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *postsServer) serveAddCommentJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	d := json.NewDecoder(req.Body)
	rawReqBody := json.RawMessage{}
	if err := d.Decode(&rawReqBody); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}
	reqContent := new(AddCommentRequest)
	unmarshaler := protojson.UnmarshalOptions{DiscardUnknown: true}
	if err = unmarshaler.Unmarshal(rawReqBody, reqContent); err != nil {
		s.handleRequestBodyError(ctx, resp, "the json request could not be decoded", err)
		return
	}

	handler := s.Posts.AddComment
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *AddCommentRequest) (*AddCommentResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AddCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AddCommentRequest) when calling interceptor")
					}
					return s.Posts.AddComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AddCommentResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AddCommentResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AddCommentResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AddCommentResponse and nil error while calling AddComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	marshaler := &protojson.MarshalOptions{UseProtoNames: true, EmitUnpopulated: !s.jsonSkipDefaults}
	respBytes, err := marshaler.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal json response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)

	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postsServer) serveAddCommentProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "AddComment")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		s.handleRequestBodyError(ctx, resp, "failed to read request body", err)
		return
	}
	reqContent := new(AddCommentRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		s.writeError(ctx, resp, malformedRequestError("the protobuf request could not be decoded"))
		return
	}

	handler := s.Posts.AddComment
	if s.interceptor != nil {
		handler = func(ctx context.Context, req *AddCommentRequest) (*AddCommentResponse, error) {
			resp, err := s.interceptor(
				func(ctx context.Context, req interface{}) (interface{}, error) {
					typedReq, ok := req.(*AddCommentRequest)
					if !ok {
						return nil, twirp.InternalError("failed type assertion req.(*AddCommentRequest) when calling interceptor")
					}
					return s.Posts.AddComment(ctx, typedReq)
				},
			)(ctx, req)
			if resp != nil {
				typedResp, ok := resp.(*AddCommentResponse)
				if !ok {
					return nil, twirp.InternalError("failed type assertion resp.(*AddCommentResponse) when calling interceptor")
				}
				return typedResp, err
			}
			return nil, err
		}
	}

	// Call service method
	var respContent *AddCommentResponse
	func() {
		defer ensurePanicResponses(ctx, resp, s.hooks)
		respContent, err = handler(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *AddCommentResponse and nil error while calling AddComment. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		s.writeError(ctx, resp, wrapInternal(err, "failed to marshal proto response"))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.Header().Set("Content-Length", strconv.Itoa(len(respBytes)))
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		ctx = callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *postsServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor1, 0
}

func (s *postsServer) ProtocGenTwirpVersion() string {
	return "v8.0.0"
}

// PathPrefix returns the base service path, in the form: "/<prefix>/<package>.<Service>/"
// that is everything in a Twirp route except for the <Method>. This can be used for routing,
// for example to identify the requests that are targeted to this service in a mux.
func (s *postsServer) PathPrefix() string {
	return baseServicePath(s.pathPrefix, "meme", "Posts")
}

var twirpFileDescriptor1 = []byte{
	// 346 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x6b, 0xea, 0x40,
	0x10, 0xc6, 0x5f, 0x9e, 0x9a, 0xf7, 0xde, 0x08, 0xaf, 0xba, 0xb4, 0x1a, 0x3c, 0x88, 0xec, 0xa9,
	0x87, 0x92, 0x82, 0x95, 0x5e, 0x25, 0x95, 0x1e, 0xa4, 0x52, 0x4a, 0x5a, 0x2f, 0xbd, 0xa9, 0x3b,
	0xa8, 0x98, 0x64, 0xb6, 0xd9, 0x15, 0x7a, 0xef, 0x1f, 0xd6, 0x7f, 0xad, 0xb8, 0xd9, 0x34, 0xc1,
	0x60, 0x6f, 0x3b, 0x5f, 0x3e, 0x7e, 0x33, 0xf3, 0x4d, 0xa0, 0x29, 0x49, 0x69, 0xe5, 0xcb, 0x94,
	0x34, 0xb1, 0x7a, 0x8c, 0x31, 0xf2, 0x31, 0x9c, 0x3d, 0x1d, 0xc4, 0x40, 0x88, 0x10, 0xdf, 0xf6,
	0xa8, 0x34, 0x63, 0x50, 0xd7, 0xf8, 0xae, 0x3d, 0x67, 0xe0, 0x5c, 0xfe, 0x0b, 0xcd, 0x9b, 0x79,
	0xf0, 0x47, 0x6e, 0x48, 0xd3, 0x54, 0x78, 0xbf, 0x8d, 0x9c, 0x97, 0xfc, 0x0a, 0x5a, 0x05, 0x40,
	0x49, 0x4a, 0x14, 0x1a, 0x37, 0x29, 0x3d, 0x4f, 0x23, 0x0b, 0xc9, 0x4b, 0xfe, 0xe1, 0x40, 0xfb,
	0x85, 0xd6, 0xeb, 0x08, 0x67, 0xdb, 0x1d, 0xe6, 0x1d, 0x6f, 0xc1, 0x5d, 0xac, 0xf4, 0x96, 0x12,
	0x63, 0xff, 0x3f, 0xec, 0xfb, 0x87, 0xd9, 0xfc, 0x8a, 0xd1, 0x0f, 0x8c, 0x2b, 0xb4, 0x6e, 0xd6,
	0x01, 0xf7, 0x00, 0xfe, 0x1e, 0xca, 0x56, 0xbc, 0x0f, 0x6e, 0xe6, 0x64, 0x7f, 0xa1, 0x3e, 0x9b,
	0x3e, 0xdc, 0xb7, 0x7e, 0x31, 0x00, 0x77, 0xfe, 0x68, 0xde, 0x0e, 0x1f, 0x01, 0x2b, 0xb3, 0xed,
	0xd4, 0x7d, 0x80, 0x68, 0xbb, 0x43, 0x35, 0xa1, 0x7d, 0x92, 0x6d, 0xdf, 0x08, 0x4b, 0x0a, 0x1f,
	0x43, 0x3b, 0x10, 0x62, 0x42, 0x71, 0x8c, 0x89, 0xfe, 0x29, 0xac, 0x53, 0x63, 0x9d, 0x03, 0x2b,
	0x03, 0xb2, 0xb6, 0xfc, 0x19, 0xba, 0x56, 0x9a, 0x50, 0x2c, 0x49, 0x61, 0x1a, 0x62, 0x22, 0x30,
	0xc5, 0xb4, 0x04, 0x72, 0xca, 0x20, 0x36, 0x80, 0xa6, 0x8c, 0x16, 0x2b, 0xdc, 0x50, 0x24, 0x30,
	0xb5, 0x5d, 0xca, 0xd2, 0xf0, 0xd3, 0x81, 0x86, 0x39, 0x0b, 0x1b, 0x41, 0x2d, 0x10, 0x82, 0x5d,
	0x64, 0x91, 0x1e, 0xdd, 0xba, 0xd7, 0x39, 0x96, 0x6d, 0x16, 0x63, 0x80, 0x22, 0x21, 0xd6, 0x3d,
	0x71, 0x8f, 0x9e, 0x57, 0xfd, 0x50, 0x00, 0x8a, 0x5d, 0x73, 0x40, 0x25, 0xbe, 0x1c, 0x50, 0x8d,
	0xe5, 0xae, 0xf1, 0x5a, 0xbb, 0x96, 0xcb, 0xa5, 0x6b, 0x7e, 0xd6, 0x9b, 0xaf, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x58, 0x34, 0xcb, 0xdb, 0xbb, 0x02, 0x00, 0x00,
}
