// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/materkov/meme9/users-service/api (interfaces: UsersAdapter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_users_adapter.go -package=mocks github.com/materkov/meme9/users-service/api UsersAdapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	users "github.com/materkov/meme9/users-service/adapters/users"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersAdapter is a mock of UsersAdapter interface.
type MockUsersAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockUsersAdapterMockRecorder
	isgomock struct{}
}

// MockUsersAdapterMockRecorder is the mock recorder for MockUsersAdapter.
type MockUsersAdapterMockRecorder struct {
	mock *MockUsersAdapter
}

// NewMockUsersAdapter creates a new mock instance.
func NewMockUsersAdapter(ctrl *gomock.Controller) *MockUsersAdapter {
	mock := &MockUsersAdapter{ctrl: ctrl}
	mock.recorder = &MockUsersAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersAdapter) EXPECT() *MockUsersAdapterMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUsersAdapter) GetByID(ctx context.Context, userID string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, userID)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUsersAdapterMockRecorder) GetByID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUsersAdapter)(nil).GetByID), ctx, userID)
}

// UpdateAvatar mocks base method.
func (m *MockUsersAdapter) UpdateAvatar(ctx context.Context, userID, avatarURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAvatar", ctx, userID, avatarURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAvatar indicates an expected call of UpdateAvatar.
func (mr *MockUsersAdapterMockRecorder) UpdateAvatar(ctx, userID, avatarURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAvatar", reflect.TypeOf((*MockUsersAdapter)(nil).UpdateAvatar), ctx, userID, avatarURL)
}
