// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: feed.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "meme.feed";

export interface FeedRequest {
  /** "all" or "subscriptions" */
  type: string;
}

export interface FeedPostResponse {
  id: string;
  text: string;
  userId: string;
  username: string;
  /** RFC3339 format */
  createdAt: string;
}

export interface FeedResponse {
  posts: FeedPostResponse[];
}

function createBaseFeedRequest(): FeedRequest {
  return { type: "" };
}

export const FeedRequest: MessageFns<FeedRequest> = {
  encode(message: FeedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FeedRequest {
    return { type: isSet(object.type) ? globalThis.String(object.type) : "" };
  },

  toJSON(message: FeedRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FeedRequest>, I>>(base?: I): FeedRequest {
    return FeedRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FeedRequest>, I>>(object: I): FeedRequest {
    const message = createBaseFeedRequest();
    message.type = object.type ?? "";
    return message;
  },
};

function createBaseFeedPostResponse(): FeedPostResponse {
  return { id: "", text: "", userId: "", username: "", createdAt: "" };
}

export const FeedPostResponse: MessageFns<FeedPostResponse> = {
  encode(message: FeedPostResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.text !== "") {
      writer.uint32(18).string(message.text);
    }
    if (message.userId !== "") {
      writer.uint32(26).string(message.userId);
    }
    if (message.username !== "") {
      writer.uint32(34).string(message.username);
    }
    if (message.createdAt !== "") {
      writer.uint32(42).string(message.createdAt);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeedPostResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeedPostResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.text = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.username = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.createdAt = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FeedPostResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      text: isSet(object.text) ? globalThis.String(object.text) : "",
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      username: isSet(object.username) ? globalThis.String(object.username) : "",
      createdAt: isSet(object.createdAt) ? globalThis.String(object.createdAt) : "",
    };
  },

  toJSON(message: FeedPostResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.text !== "") {
      obj.text = message.text;
    }
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.username !== "") {
      obj.username = message.username;
    }
    if (message.createdAt !== "") {
      obj.createdAt = message.createdAt;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FeedPostResponse>, I>>(base?: I): FeedPostResponse {
    return FeedPostResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FeedPostResponse>, I>>(object: I): FeedPostResponse {
    const message = createBaseFeedPostResponse();
    message.id = object.id ?? "";
    message.text = object.text ?? "";
    message.userId = object.userId ?? "";
    message.username = object.username ?? "";
    message.createdAt = object.createdAt ?? "";
    return message;
  },
};

function createBaseFeedResponse(): FeedResponse {
  return { posts: [] };
}

export const FeedResponse: MessageFns<FeedResponse> = {
  encode(message: FeedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.posts) {
      FeedPostResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): FeedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseFeedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.posts.push(FeedPostResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): FeedResponse {
    return {
      posts: globalThis.Array.isArray(object?.posts) ? object.posts.map((e: any) => FeedPostResponse.fromJSON(e)) : [],
    };
  },

  toJSON(message: FeedResponse): unknown {
    const obj: any = {};
    if (message.posts?.length) {
      obj.posts = message.posts.map((e) => FeedPostResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<FeedResponse>, I>>(base?: I): FeedResponse {
    return FeedResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<FeedResponse>, I>>(object: I): FeedResponse {
    const message = createBaseFeedResponse();
    message.posts = object.posts?.map((e) => FeedPostResponse.fromPartial(e)) || [];
    return message;
  },
};

/** Feed service */
export type FeedDefinition = typeof FeedDefinition;
export const FeedDefinition = {
  name: "Feed",
  fullName: "meme.feed.Feed",
  methods: {
    getFeed: {
      name: "GetFeed",
      requestType: FeedRequest,
      requestStream: false,
      responseType: FeedResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
