// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.3
// source: subscriptions.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "meme.subscriptions";

export interface SubscribeRequest {
  userId: string;
}

export interface SubscribeResponse {
  subscribed: boolean;
}

export interface GetFollowingRequest {
  userId: string;
}

export interface GetFollowingResponse {
  userIds: string[];
}

export interface IsSubscribedRequest {
  subscriberId: string;
  targetUserId: string;
}

export interface IsSubscribedResponse {
  subscribed: boolean;
}

function createBaseSubscribeRequest(): SubscribeRequest {
  return { userId: "" };
}

export const SubscribeRequest: MessageFns<SubscribeRequest> = {
  encode(message: SubscribeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeRequest {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: SubscribeRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeRequest>, I>>(base?: I): SubscribeRequest {
    return SubscribeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeRequest>, I>>(object: I): SubscribeRequest {
    const message = createBaseSubscribeRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseSubscribeResponse(): SubscribeResponse {
  return { subscribed: false };
}

export const SubscribeResponse: MessageFns<SubscribeResponse> = {
  encode(message: SubscribeResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscribed !== false) {
      writer.uint32(8).bool(message.subscribed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SubscribeResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSubscribeResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.subscribed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SubscribeResponse {
    return { subscribed: isSet(object.subscribed) ? globalThis.Boolean(object.subscribed) : false };
  },

  toJSON(message: SubscribeResponse): unknown {
    const obj: any = {};
    if (message.subscribed !== false) {
      obj.subscribed = message.subscribed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SubscribeResponse>, I>>(base?: I): SubscribeResponse {
    return SubscribeResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SubscribeResponse>, I>>(object: I): SubscribeResponse {
    const message = createBaseSubscribeResponse();
    message.subscribed = object.subscribed ?? false;
    return message;
  },
};

function createBaseGetFollowingRequest(): GetFollowingRequest {
  return { userId: "" };
}

export const GetFollowingRequest: MessageFns<GetFollowingRequest> = {
  encode(message: GetFollowingRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFollowingRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFollowingRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFollowingRequest {
    return { userId: isSet(object.userId) ? globalThis.String(object.userId) : "" };
  },

  toJSON(message: GetFollowingRequest): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetFollowingRequest>, I>>(base?: I): GetFollowingRequest {
    return GetFollowingRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetFollowingRequest>, I>>(object: I): GetFollowingRequest {
    const message = createBaseGetFollowingRequest();
    message.userId = object.userId ?? "";
    return message;
  },
};

function createBaseGetFollowingResponse(): GetFollowingResponse {
  return { userIds: [] };
}

export const GetFollowingResponse: MessageFns<GetFollowingResponse> = {
  encode(message: GetFollowingResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.userIds) {
      writer.uint32(10).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetFollowingResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetFollowingResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userIds.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetFollowingResponse {
    return {
      userIds: globalThis.Array.isArray(object?.userIds) ? object.userIds.map((e: any) => globalThis.String(e)) : [],
    };
  },

  toJSON(message: GetFollowingResponse): unknown {
    const obj: any = {};
    if (message.userIds?.length) {
      obj.userIds = message.userIds;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetFollowingResponse>, I>>(base?: I): GetFollowingResponse {
    return GetFollowingResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetFollowingResponse>, I>>(object: I): GetFollowingResponse {
    const message = createBaseGetFollowingResponse();
    message.userIds = object.userIds?.map((e) => e) || [];
    return message;
  },
};

function createBaseIsSubscribedRequest(): IsSubscribedRequest {
  return { subscriberId: "", targetUserId: "" };
}

export const IsSubscribedRequest: MessageFns<IsSubscribedRequest> = {
  encode(message: IsSubscribedRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscriberId !== "") {
      writer.uint32(10).string(message.subscriberId);
    }
    if (message.targetUserId !== "") {
      writer.uint32(18).string(message.targetUserId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IsSubscribedRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIsSubscribedRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.subscriberId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.targetUserId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IsSubscribedRequest {
    return {
      subscriberId: isSet(object.subscriberId) ? globalThis.String(object.subscriberId) : "",
      targetUserId: isSet(object.targetUserId) ? globalThis.String(object.targetUserId) : "",
    };
  },

  toJSON(message: IsSubscribedRequest): unknown {
    const obj: any = {};
    if (message.subscriberId !== "") {
      obj.subscriberId = message.subscriberId;
    }
    if (message.targetUserId !== "") {
      obj.targetUserId = message.targetUserId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IsSubscribedRequest>, I>>(base?: I): IsSubscribedRequest {
    return IsSubscribedRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IsSubscribedRequest>, I>>(object: I): IsSubscribedRequest {
    const message = createBaseIsSubscribedRequest();
    message.subscriberId = object.subscriberId ?? "";
    message.targetUserId = object.targetUserId ?? "";
    return message;
  },
};

function createBaseIsSubscribedResponse(): IsSubscribedResponse {
  return { subscribed: false };
}

export const IsSubscribedResponse: MessageFns<IsSubscribedResponse> = {
  encode(message: IsSubscribedResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.subscribed !== false) {
      writer.uint32(8).bool(message.subscribed);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): IsSubscribedResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseIsSubscribedResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.subscribed = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): IsSubscribedResponse {
    return { subscribed: isSet(object.subscribed) ? globalThis.Boolean(object.subscribed) : false };
  },

  toJSON(message: IsSubscribedResponse): unknown {
    const obj: any = {};
    if (message.subscribed !== false) {
      obj.subscribed = message.subscribed;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<IsSubscribedResponse>, I>>(base?: I): IsSubscribedResponse {
    return IsSubscribedResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<IsSubscribedResponse>, I>>(object: I): IsSubscribedResponse {
    const message = createBaseIsSubscribedResponse();
    message.subscribed = object.subscribed ?? false;
    return message;
  },
};

/** Subscriptions service */
export type SubscriptionsDefinition = typeof SubscriptionsDefinition;
export const SubscriptionsDefinition = {
  name: "Subscriptions",
  fullName: "meme.subscriptions.Subscriptions",
  methods: {
    subscribe: {
      name: "Subscribe",
      requestType: SubscribeRequest,
      requestStream: false,
      responseType: SubscribeResponse,
      responseStream: false,
      options: {},
    },
    unsubscribe: {
      name: "Unsubscribe",
      requestType: SubscribeRequest,
      requestStream: false,
      responseType: SubscribeResponse,
      responseStream: false,
      options: {},
    },
    getStatus: {
      name: "GetStatus",
      requestType: SubscribeRequest,
      requestStream: false,
      responseType: SubscribeResponse,
      responseStream: false,
      options: {},
    },
    getFollowing: {
      name: "GetFollowing",
      requestType: GetFollowingRequest,
      requestStream: false,
      responseType: GetFollowingResponse,
      responseStream: false,
      options: {},
    },
    isSubscribed: {
      name: "IsSubscribed",
      requestType: IsSubscribedRequest,
      requestStream: false,
      responseType: IsSubscribedResponse,
      responseStream: false,
      options: {},
    },
  },
} as const;

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
