version: "3.9"
services:
  redis:
    image: "redis:alpine"
  mysql:
    image: "mysql"
    environment:
      MYSQL_ROOT_PASSWORD: example
  postgres:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    volumes:
      - './data/config:/etc/gitlab'
      - './data/logs:/var/log/gitlab'
      - './data/data:/var/opt/gitlab'
