// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/materkov/meme9/likes-service/api (interfaces: MongoAdapter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_mongo_adapter.go -package=mocks github.com/materkov/meme9/likes-service/api MongoAdapter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMongoAdapter is a mock of MongoAdapter interface.
type MockMongoAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockMongoAdapterMockRecorder
	isgomock struct{}
}

// MockMongoAdapterMockRecorder is the mock recorder for MockMongoAdapter.
type MockMongoAdapterMockRecorder struct {
	mock *MockMongoAdapter
}

// NewMockMongoAdapter creates a new mock instance.
func NewMockMongoAdapter(ctrl *gomock.Controller) *MockMongoAdapter {
	mock := &MockMongoAdapter{ctrl: ctrl}
	mock.recorder = &MockMongoAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMongoAdapter) EXPECT() *MockMongoAdapterMockRecorder {
	return m.recorder
}

// GetLikedByUser mocks base method.
func (m *MockMongoAdapter) GetLikedByUser(ctx context.Context, userID string, postIDs []string) (map[string]bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikedByUser", ctx, userID, postIDs)
	ret0, _ := ret[0].(map[string]bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikedByUser indicates an expected call of GetLikedByUser.
func (mr *MockMongoAdapterMockRecorder) GetLikedByUser(ctx, userID, postIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikedByUser", reflect.TypeOf((*MockMongoAdapter)(nil).GetLikedByUser), ctx, userID, postIDs)
}

// GetLikers mocks base method.
func (m *MockMongoAdapter) GetLikers(ctx context.Context, postID, pageToken string, count int) ([]string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikers", ctx, postID, pageToken, count)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetLikers indicates an expected call of GetLikers.
func (mr *MockMongoAdapterMockRecorder) GetLikers(ctx, postID, pageToken, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikers", reflect.TypeOf((*MockMongoAdapter)(nil).GetLikers), ctx, postID, pageToken, count)
}

// GetLikesCounts mocks base method.
func (m *MockMongoAdapter) GetLikesCounts(ctx context.Context, postIDs []string) (map[string]int32, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLikesCounts", ctx, postIDs)
	ret0, _ := ret[0].(map[string]int32)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLikesCounts indicates an expected call of GetLikesCounts.
func (mr *MockMongoAdapterMockRecorder) GetLikesCounts(ctx, postIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLikesCounts", reflect.TypeOf((*MockMongoAdapter)(nil).GetLikesCounts), ctx, postIDs)
}

// IsLiked mocks base method.
func (m *MockMongoAdapter) IsLiked(ctx context.Context, postID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsLiked", ctx, postID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsLiked indicates an expected call of IsLiked.
func (mr *MockMongoAdapterMockRecorder) IsLiked(ctx, postID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsLiked", reflect.TypeOf((*MockMongoAdapter)(nil).IsLiked), ctx, postID, userID)
}

// Like mocks base method.
func (m *MockMongoAdapter) Like(ctx context.Context, postID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Like", ctx, postID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Like indicates an expected call of Like.
func (mr *MockMongoAdapterMockRecorder) Like(ctx, postID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Like", reflect.TypeOf((*MockMongoAdapter)(nil).Like), ctx, postID, userID)
}

// Unlike mocks base method.
func (m *MockMongoAdapter) Unlike(ctx context.Context, postID, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlike", ctx, postID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlike indicates an expected call of Unlike.
func (mr *MockMongoAdapterMockRecorder) Unlike(ctx, postID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlike", reflect.TypeOf((*MockMongoAdapter)(nil).Unlike), ctx, postID, userID)
}
