// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: json_api.proto

package json_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	JsonAPI_GetFeed_FullMethodName               = "/meme.json_api.JsonAPI/GetFeed"
	JsonAPI_Publish_FullMethodName               = "/meme.json_api.JsonAPI/Publish"
	JsonAPI_Login_FullMethodName                 = "/meme.json_api.JsonAPI/Login"
	JsonAPI_Register_FullMethodName              = "/meme.json_api.JsonAPI/Register"
	JsonAPI_GetUserPosts_FullMethodName          = "/meme.json_api.JsonAPI/GetUserPosts"
	JsonAPI_Subscribe_FullMethodName             = "/meme.json_api.JsonAPI/Subscribe"
	JsonAPI_Unsubscribe_FullMethodName           = "/meme.json_api.JsonAPI/Unsubscribe"
	JsonAPI_GetSubscriptionStatus_FullMethodName = "/meme.json_api.JsonAPI/GetSubscriptionStatus"
)

// JsonAPIClient is the client API for JsonAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// JSON API service definitions for REST endpoints
type JsonAPIClient interface {
	// Feed API - GET /api/feed
	GetFeed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error)
	// Publish API - POST /api/publish
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Login API - POST /api/login
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// Register API - POST /api/register
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	// UserPosts API - POST /api/userPosts
	GetUserPosts(ctx context.Context, in *UserPostsRequest, opts ...grpc.CallOption) (*UserPostsResponse, error)
	// Subscribe API - POST /api/subscribe
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	// Unsubscribe API - POST /api/unsubscribe
	Unsubscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
	// SubscriptionStatus API - POST /api/subscriptionStatus
	GetSubscriptionStatus(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error)
}

type jsonAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewJsonAPIClient(cc grpc.ClientConnInterface) JsonAPIClient {
	return &jsonAPIClient{cc}
}

func (c *jsonAPIClient) GetFeed(ctx context.Context, in *FeedRequest, opts ...grpc.CallOption) (*FeedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FeedResponse)
	err := c.cc.Invoke(ctx, JsonAPI_GetFeed_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonAPIClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, JsonAPI_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonAPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, JsonAPI_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonAPIClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, JsonAPI_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonAPIClient) GetUserPosts(ctx context.Context, in *UserPostsRequest, opts ...grpc.CallOption) (*UserPostsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserPostsResponse)
	err := c.cc.Invoke(ctx, JsonAPI_GetUserPosts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonAPIClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, JsonAPI_Subscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonAPIClient) Unsubscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, JsonAPI_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jsonAPIClient) GetSubscriptionStatus(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SubscribeResponse)
	err := c.cc.Invoke(ctx, JsonAPI_GetSubscriptionStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JsonAPIServer is the server API for JsonAPI service.
// All implementations must embed UnimplementedJsonAPIServer
// for forward compatibility.
//
// JSON API service definitions for REST endpoints
type JsonAPIServer interface {
	// Feed API - GET /api/feed
	GetFeed(context.Context, *FeedRequest) (*FeedResponse, error)
	// Publish API - POST /api/publish
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Login API - POST /api/login
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	// Register API - POST /api/register
	Register(context.Context, *RegisterRequest) (*LoginResponse, error)
	// UserPosts API - POST /api/userPosts
	GetUserPosts(context.Context, *UserPostsRequest) (*UserPostsResponse, error)
	// Subscribe API - POST /api/subscribe
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	// Unsubscribe API - POST /api/unsubscribe
	Unsubscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	// SubscriptionStatus API - POST /api/subscriptionStatus
	GetSubscriptionStatus(context.Context, *SubscribeRequest) (*SubscribeResponse, error)
	mustEmbedUnimplementedJsonAPIServer()
}

// UnimplementedJsonAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedJsonAPIServer struct{}

func (UnimplementedJsonAPIServer) GetFeed(context.Context, *FeedRequest) (*FeedResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetFeed not implemented")
}
func (UnimplementedJsonAPIServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedJsonAPIServer) Login(context.Context, *LoginRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedJsonAPIServer) Register(context.Context, *RegisterRequest) (*LoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedJsonAPIServer) GetUserPosts(context.Context, *UserPostsRequest) (*UserPostsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserPosts not implemented")
}
func (UnimplementedJsonAPIServer) Subscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedJsonAPIServer) Unsubscribe(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedJsonAPIServer) GetSubscriptionStatus(context.Context, *SubscribeRequest) (*SubscribeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscriptionStatus not implemented")
}
func (UnimplementedJsonAPIServer) mustEmbedUnimplementedJsonAPIServer() {}
func (UnimplementedJsonAPIServer) testEmbeddedByValue()                 {}

// UnsafeJsonAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to JsonAPIServer will
// result in compilation errors.
type UnsafeJsonAPIServer interface {
	mustEmbedUnimplementedJsonAPIServer()
}

func RegisterJsonAPIServer(s grpc.ServiceRegistrar, srv JsonAPIServer) {
	// If the following call panics, it indicates UnimplementedJsonAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&JsonAPI_ServiceDesc, srv)
}

func _JsonAPI_GetFeed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FeedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).GetFeed(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_GetFeed_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).GetFeed(ctx, req.(*FeedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonAPI_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonAPI_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonAPI_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).Register(ctx, req.(*RegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonAPI_GetUserPosts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserPostsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).GetUserPosts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_GetUserPosts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).GetUserPosts(ctx, req.(*UserPostsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonAPI_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_Subscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonAPI_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).Unsubscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JsonAPI_GetSubscriptionStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JsonAPIServer).GetSubscriptionStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: JsonAPI_GetSubscriptionStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JsonAPIServer).GetSubscriptionStatus(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// JsonAPI_ServiceDesc is the grpc.ServiceDesc for JsonAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JsonAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "meme.json_api.JsonAPI",
	HandlerType: (*JsonAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFeed",
			Handler:    _JsonAPI_GetFeed_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _JsonAPI_Publish_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _JsonAPI_Login_Handler,
		},
		{
			MethodName: "Register",
			Handler:    _JsonAPI_Register_Handler,
		},
		{
			MethodName: "GetUserPosts",
			Handler:    _JsonAPI_GetUserPosts_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _JsonAPI_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _JsonAPI_Unsubscribe_Handler,
		},
		{
			MethodName: "GetSubscriptionStatus",
			Handler:    _JsonAPI_GetSubscriptionStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "json_api.proto",
}
