POST http://localhost:8000/gql
Content-Type: application/json

{
  "node": {
    "include": true,
    "id": "User:10",
    "inner": {
      "onPost": {
        "text": {
          "include": true
        }
      },
      "onUser": {
        "name": {
          "include": true
        }
      }
    }
  }
}

