name: functional-tests
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0.11
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

      redis:
        image: redis:5.0.5
        ports:
          - 6379:6379

    steps:
      - name: Set up Go 1.21
        uses: actions/setup-go@v1
        with:
          go-version: 1.21
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Build web app
        run: cd web6 && go build cmd/main.go

      - name: Run web app in background
        run: ./web6/main &

      - name: Put api config
        run: sudo mkdir -p /apps/meme9-config && sudo echo "{}" >/apps/meme9-config/api.json

      - name: Build api app
        run: cd api && go build cmd/main.go

      - name: Run api app in background
        run: ./api/main &

      - name: Init mysql schema
        run: mysql -h localhost -P 3306 --protocol=tcp -u root --password=root < migrations/01_init.sql

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Set up pip
        run: python -m pip install --upgrade pip

      - name: Set up pytest
        run: pip install pytest

      - name: Functional tests
        run: cd tests && pytest test_posts.py
