name: web
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      postgres:
        image: mysql:8.0.11
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306

      redis:
        image: redis:5.0.5
        ports:
          - 6379:6379

    steps:
      - name: Set up Go 1.16
        uses: actions/setup-go@v1
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: build
        run: cd web4 && go build cmd

      #- name: linters
      #  run: make lint-all

      #- name: test
      #  run: cd web && go test -v ./...
